spring.application.name=banking-ai

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.uoegpyjelndpneitqhft
spring.datasource.password=Pranjali@1405

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true